let resumeData = {
    "name": "Casey Jardin",
    "location":"Atlanta, GA",
    "email": "caseyjardin@gmail.com",
    "header":{
      "background":"images/header-background.jpg",
      "specialization": "JavaScript and Python Engineer",
      "introduction": "I am highly adaptable, I love learning new technologies and I am passionate about various parts of frontend development. I like to learn about backend methodologies by creating interactive community-driven Discord & Slack chat bots in my free time.",
      "networks":[
        {
          "name":"linkedin",
          "url":"https://www.linkedin.com/in/caseyjardin",
          "className":"fab fa-linkedin"
        },
        {
          "name":"codepen",
          "url":"https://codepen.io/alpha1337/",
          "className":"fab fa-codepen"
        },
        {
          "name":"github",
          "url":"http://github.com/caseyjardin",
          "className":"fab fa-github"
        },
        {
          "name":"instagram",
          "url":"https://instagram.com/foxdenpremium",
          "className":"fab fa-instagram"
        },
        {
          "name":"twitter",
          "url":"https://twitter.com/foxdenpremium",
          "className":"fab fa-twitter"
        }
      ],
    },
    "about":{
      "description":"Senior Frontend Engineer with more than 7+ years of experience building pixel perfect websites and digital signage. Highly adaptable to various working environments having positioned for startups, digital agencies, and fortune 500 companies. Passionate about UI development for client-side web apps. I'm eager to advance my career with a team of talented like-minded individuals who are passionate about collaboration, communication, and delivering high-quality products.",
      "networks":[
        {
          "name":"gmail",
          "url":"mailto:caseyjardin@gmail.com",
          "icon":"fab fa-google"
        },
        {
          "name":"whatsapp",
          "url":"https://wa.me/12345678900",
          "icon":"fab fa-whatsapp"
        },
        {
          "name":"ForFoxSake#7077",
          "url": null,
          "icon":"fab fa-discord"
        },
        {
          "name":"funkopoprox",
          "url": null,
          "icon":"fab fa-playstation"
        },
        {
          "name":"alpha1337#1197",
          "url": null,
          "icon":"fab fa-battle-net"
        },
      ],
    },
    "work":[
    {
      "company":"Black Airplane",
      "logo": "./images/logo/blackairplane.png",
      "title":"Software Engineer",
      "description": [
        "Primary role consists of leading the front-end efforts for optimizing Node.js build processes & creating responsive static HTML templates as deliverables to integrate into dynamic content management systems. In addition to template creation, I’ve also explored the back-end integration processes which generate dynamic data-driven templates in the Wordpress environment utilizing PHP methods to bring data to the UI.",
      ],
      "achievements": null,
      "skills": null,
      "samples": null,
      "startDate":"2019",
      "endDate":"2019",
    },
    {
      "company":"Kefi",
      "logo": "./images/logo/kefi.png",
      "title":"Black Airplane",
      "description": null,
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate":"2019",
      "endDate":"2019",
    },
    {
      "company":"Superior Essex",
      "logo": "./images/logo/superioressex.png",
      "title":"Black Airplane",
      "description": null,
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate":"2019",
      "endDate":"2019",
    },
    {
      "company":"Arke Systems",
      "logo": "./images/logo/arke.jpeg",
      "title":"Senior Frontend Developer",
      "description": [
        "This project tasked my team to replace a third-party integration and build a new corporate-wide online ordering platform from scratch. Our solution has successfully been deployed across each of their brands.",
        "As the lead frontend developer on this project I collaborated with business teams to define scope of work, estimates, delegate tasks to other developers and ramp up new team members in an end-to-end TDD environment.",
        "In addition to my regular tasks as a developer I took the lead with authoring technical documentation, interactive style guides while adhering to to WCAG Accessibility requirements."
      ],
      "achievements": null,
      "skills": null,
      "samples": null,
      "startDate":"2019",
      "endDate":"2019",
    },
    {
      "company":"Bloomin' Brands",
      "logo": "./images/logo/bloomin.png",
      "title":"Arke Systems",
      "description": null,
      "achievements":[
        "Met and exceeded all WCAG accessibility standards achieving an AA-level experience.",
        "Completely overhauled the corporate-wide online ordering platform from end-to-end.",
        "Conducted code quality reviews of my peers in a deadline-oriented Agile environment as scrum master for my particular domain.",
        "Collaborated with Sitecore engineers to deploy dynamically data-driven content to the presentation layer of each web application.",
        "Developed a highly-scalable 'white-labeled' library of responsive web templates to refresh all brand sites and online ordering platforms.",
        "Resolved critical UX issues by monitoring Google Analytics user behaviors which greatly reduced overall bounce rates thus creating a higher percentage of conversions.",
        "Integrated successfully with client-facing QA and Design teams to author technical documentation and interactive style guides which continue to meet and exceed MVP business requirements.",
    ],
      "skills":[
        {type: "Bootstrap", level: 100},
        {type: "jQuery", level: 100},
        {type: "Architecture", level: 90},
        {type: "Documentation", level: 80},
        {type: "devOps", level: 75},
        {type: "Accessibility", level: 70},
        {type: "REST API", level: 60},
        {type: "SQL", level: 35},
        {type: "Sitecore", level: 25},
        {type: "PHP", level: 15},
      ],
      "samples": [
        "bloomin/outback-steakhouse.png",
        "bloomin/carabbas.png",
        "bloomin/bonefish-grill.png",
        "bloomin/flemings.png",
      ],
      "startDate":"2019",
      "endDate":"2019",
    },
    {
      "company":"Publicis Sapient",
      "logo": "./images/logo/sapient.png",
      "title":"Senior Frontend Engineer II",
      "description": [
        "Focused on digitally transforming some of the World’s leading automobile, tire manufacturing, and multinational insurance corporations to reconnect brands to their consumers. Markedly increased performance metrics, website maintainability and scalability by meticulously compiling self-documenting component based solutions. These improvements have strengthened client conversions by a significant margin which continues to have measurable business impact today.",
        "Aided in defining business rules and gathering technical requirements with client partners in the business, marketing, and operations domains to troubleshoot and resolve complex challenges. Additional responsibilities for my role include interviewing new hire candidates, mentoring interns, managing development tracks and authoring release notes for the client."
      ],
      "achievements":null,
      "skills":null,
      "samples": null,
      "startDate": null,
      "endDate": null,
    },
    {
      "company":"Mercedes-Benz",
      "logo": "./images/logo/mercedes.png",
      "title":"Publicis Sapient",
      "description": "",
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate": null,
      "endDate": null,
    },
    {
        "company":"Southern Glazers",
        "logo": "./images/logo/southernglazers.png",
        "title":"Publicis Sapient",
        "description": "",
        "achievements":[""],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
    {
      "company":"B.F. Goodrich",
      "logo": "./images/logo/bfgoodrich.png",
      "title":"Publicis Sapient",
      "description": "",
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate": null,
      "endDate": null,
    },
    {
      "company":"AIG / Valic",
      "logo": "./images/logo/valic.png",
      "title":"Publicis Sapient",
      "description": "",
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate": null,
      "endDate": null,
    },
    {
      "company":"Michelin",
      "logo": "./images/logo/michelin.jpg",
      "title":"Publicis Sapient",
      "description": null,
      "achievements":[
        "Developed an interactive digital signage kiosk which has been displayed in over 20 Costco locations in America on Angular platform.",
        "Organized, manipulated and delivered dynamic vehicle and tire data to the UI utilizing the REST API.",
        "Configured hardware for installations by cloning operating system settings and deployed to multiple remote devices.",
        "Optimized adopted source code which significantly improved app performance which met and exceeded client expectations.",
        "Lead MVP QA analysis and delivered final product ahead of schedule.",
        "Worked directly with focus groups to enhance user experience.",
        "Developed an interactive touch-sensitive 360 degree product spinner and various other reusable components"
      ],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "REST API", level: 90},
        {type: "Handlebars", level: 85},
        {type: "devOps", level: 75},
        {type: "Angular 1.5", level: 50},
        {type: "Grunt", level: 30},
        {type: "Node.js", level: 25},
      ],
      "samples": [
        "tire-compare/1.jpg",
        "tire-compare/2.jpg",
        "tire-compare/3.jpg",
        "tire-compare/4.jpg",
        "tire-compare/5.jpg",
      ],
      "startDate": null,
      "endDate": null,
    },
    {
      "company":"Iconologic",
      "logo": "./images/logo/iconologic.png",
      "title":"Interactive Developer",
      "description": [
        "Lead digital development track from initial strategy and design phases to production and delivery. Beyond programming, responsibilities included authoring technical documentation, defining content and functionality requirements and teaching the client how to oversee the project going forward. My efforts yielded some of the largest profit margins in the agencies 30+ year history.",
        "Successfully developed a proprietary digital signage framework for the hospitality and real estate markets. This platform achieved and exceeded all accessibility standards and allowed clients to effortlessly influence and deploy new content remotely.",
        "In addition to programming, I conducted training sessions with clients to demonstrate the features of the platform and how to effectively deploy engaging content. Iconologic also empowered me to mentor interactive development students interested in entering the marketing and advertising industry during an annual internship program.",
      ],
      "achievements":null,
      "skills":null,
      "samples": null,
      "startDate": null,
      "endDate": null,
    },
    {
      "company":"North American Properties",
      "logo": "./images/logo/avalon.jpeg",
      "title":"Iconologic",
      "description": "",
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate": null,
      "endDate": null,
    },
    {
      "company":"Bard Medical",
      "logo": "./images/logo/bard.jpeg",
      "title":"Iconologic",
      "description": "",
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate": null,
      "endDate": null,
    },
    {
      "company":"Chick-fil-A",
      "logo": "./images/logo/chickfila.jpeg",
      "title":"Iconologic",
      "description": "",
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate": null,
      "endDate": null,
    },
    {
      "company":"Square on Fifth",
      "logo": "./images/logo/sq5.jpeg",
      "title":"Iconologic",
      "description": "",
      "achievements":[""],
      "skills":[
        {type: "HTML5 / CSS3", level: 100},
        {type: "JavaScript", level: 100},
        {type: "Squarespace", level: 100},
        {type: "Webpack", level: 100},
        {type: "React", level: 80},
        {type: "SQL", level: 60},
        {type: "Vue", level: 60},
        {type: "PHP", level: 50},
        {type: "Wordpress", level: 50},
        {type: "Laravel", level: 25},
      ],
      "samples": [],
      "startDate": null,
      "endDate": null,
    },
  ],
    "freelance":[
      {
        "company":"Foxden Solutions",
        "logo": "./images/logo/foxden.jpg",
        "title":"Owner, Full-stack Software Engineer",
        "description": [
          "",
        ],
        "achievements":[
          ""
        ],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
      {
        "company":"Funko Dojo",
        "logo": "./images/logo/funkodojo.png",
        "title":"Full-stack Software Engineer",
        "description": "",
        "achievements":[
          ""
        ],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
      {
        "company":"Imbibe Design",
        "logo": "./images/logo/imbibe.jpg",
        "title":"Interactive Developer",
        "description": "",
        "achievements":[
          ""
        ],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
      {
        "company":"Freight Kitchen & Tap",
        "logo": "./images/logo/freight.png",
        "title":"Brand Identity, Web Developer. Graphic Designer",
        "description": "",
        "achievements":[
          ""
        ],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
      {
        "company":"Collins Jewelers",
        "logo": "./images/logo/collins.png",
        "title":"Brand Identity, Web Developer & Designer",
        "description": "",
        "achievements":[
          ""
        ],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
      {
        "company":"League of Legends",
        "logo": "./images/logo/league.jpg",
        "title":"Graphic Designer",
        "description": "",
        "achievements":[
          ""
        ],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
      {
        "company":"The Merton Show",
        "logo": "./images/logo/merton.png",
        "title":"Brand Identity, Web Developer & Designer",
        "description": "",
        "achievements":[
          ""
        ],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
      {
        "company":"Mindless Self Indulgence",
        "logo": "./images/logo/msi.png",
        "title":"Brand Identity, Graphic Designer",
        "description": "",
        "achievements":[
          ""
        ],
        "skills":[
          {type: "HTML5 / CSS3", level: 100},
          {type: "JavaScript", level: 100},
          {type: "Squarespace", level: 100},
          {type: "Webpack", level: 100},
          {type: "React", level: 80},
          {type: "SQL", level: 60},
          {type: "Vue", level: 60},
          {type: "PHP", level: 50},
          {type: "Wordpress", level: 50},
          {type: "Laravel", level: 25},
        ],
        "samples": [],
        "startDate": null,
        "endDate": null,
      },
    ],
  };
  
  export default resumeData

// TODO: portfolio videos should be dynamic and optional
